version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/

hooks:
  BeforeInstall:
    - location: Scripts/installdep.sh
      timeout: 300
  AfterInstall:
    - location: scripts/afterbuild.sh
      timeout: 300
  ApplicationStart:
    - location: scripts/laststage.sh
      timeout: 300
