version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/

hooks:
  BeforeInstall:
    - location: Scripts/installdep.sh
      timeout: 300
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
  ValidateService:
    - location: scripts/health_check.sh
      timeout: 300

