version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 700
      runas: root
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 700
      runas: root
  ApplicationStart:
    - location: scripts/start_application.sh
      timeout: 700
      runas: root
