version: 0.2

phases:
  install:
    commands:
      - echo "Navigating to frontend directory..."
      - sudo npm install

  pre_build:
    commands:
      - echo "Pre-building tasks (if any)..."

  build:
    commands:
      - echo "Building the frontend application..."
      - sudo npm run build   # This will trigger the build process for your frontend

  post_build:
    commands:
      - echo "Copying build files to Nginx directory..."
      - pwd
      - ls -l

artifacts:
  files:
    - '**/*'
  base-directory: /path/to/your/frontend/directory/build  # This should point to your actual build output directory
