version: 0.2

phases:
  install:
    commands:
      - echo "Navigating to frontend directory..."

  pre_build:
    commands:
      - echo "Pre-building tasks (if any)..."

  build:
    commands:
      - echo "Building the frontend application..."

  post_build:
    commands:
      - echo "Copying build files to Nginx directory"

artifacts:
  files:
    - appspec.yaml
    - buildspec.yaml
    - scripts/**
    - TODO/**
