version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20.18.1  # Specify the Node.js version you need
    commands:
      - pwd
      - ls
      - echo one phase done****************

  build:
    commands:
      - cd /TODO/todo-frontend/public
      - pwd
      - npm run build
      - echo two phase done******************

artifacts:
  files:
    - '**/*'
